services:
  node:
    image: node
    build:
      context: .
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_DOMAIN=${APP_DOMAIN}
      - APP_PORT=${APP_PORT}
      - APP_URL=${APP_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/sayyes
      - IMGBB_API_KEY=${IMGBB_API_KEY}
      - FACEBOOK_PIXEL_ID=${FACEBOOK_PIXEL_ID}
      - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
      - MAILJET_API_KEY=${MAILJET_API_KEY}
      - MAILJET_API_SECRET=${MAILJET_API_SECRET}
      - MIRO_CLIENT_ID=${MIRO_CLIENT_ID}
      - MIRO_CLIENT_SECRET=${MIRO_CLIENT_SECRET}
      - MIRO_ACCESS_TOKEN=${MIRO_ACCESS_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - STATIC_URL=${STATIC_URL}
      - STORAGE_URL=${STORAGE_URL}
      - TWILIO_ACCOUNT_ID=${TWILIO_ACCOUNT_ID}
      - TWILIO_API_KEY=${TWILIO_API_KEY}
      - TWILIO_API_SECRET=${TWILIO_API_SECRET}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_CHAT_SERVICE_ID=${TWILIO_CHAT_SERVICE_ID}
      - TWILIO_SYNC_SERVICE_ID=${TWILIO_SYNC_SERVICE_ID}
      - VKONTAKTE_CLIENT_ID=${VKONTAKTE_CLIENT_ID}
      - VKONTAKTE_CLIENT_SECRET=${VKONTAKTE_CLIENT_SECRET}
      - VKONTAKTE_CALLBACK_URL=${VKONTAKTE_CALLBACK_URL}
      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}
      - YANDEX_CALLBACK_URL=${YANDEX_CALLBACK_URL}
      - YANDEX_CLOUD_ACCESS_KEY_ID=${YANDEX_CLOUD_ACCESS_KEY_ID}
      - YANDEX_CLOUD_SECRET_ACCESS_KEY=${YANDEX_CLOUD_SECRET_ACCESS_KEY}
      - YANDEX_CLOUD_STORAGE_ENDPOINT=${YANDEX_CLOUD_STORAGE_ENDPOINT}
      - YANDEX_CLOUD_STORAGE_REGION=${YANDEX_CLOUD_STORAGE_REGION}
      - YANDEX_CLOUD_STORAGE_BUCKET=${YANDEX_CLOUD_STORAGE_BUCKET}
      - YANDEX_METRIKA_ID=${YANDEX_METRIKA_ID}
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
      - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
      - ZOOM_API_KEY=${ZOOM_API_KEY}
      - ZOOM_API_SECRET=${ZOOM_API_SECRET}
    ports:
      - ${APP_PORT}:3000
    networks:
      - local-network
    volumes:
      - ./public:/app/public
      - /etc/ssl:/etc/ssl

  mongodb:
    image: mongo
    networks:
      - local-network
    ports:
      - 27017:27017
    volumes:
      - ${DB_STORAGE_PATH}:/data/db

networks:
  local-network:
    driver: bridge
