export const defaultI18n = {
    restart: 'Играть заново',
    rewind: 'Назад на {seektime} сек',
    play: 'Играть',
    pause: 'Пауза',
    fastForward: 'Вперед на {seektime} сек',
    seek: 'Найти',
    played: 'Проиграно',
    buffered: 'Buffered',
    currentTime: 'Текущее время',
    duration: 'Продолжительность',
    volume: 'Звук',
    mute: 'Выключить звук',
    unmute: 'Включить звук',
    enableCaptions: 'Включить субтитры',
    disableCaptions: 'Отключить субтитры',
    enterFullscreen: 'Включить полноэкранный режим',
    exitFullscreen: 'Выйти из полноэкранного режима',
    frameTitle: 'Плеер для {title}',
    captions: 'Субтитры',
    settings: 'Настройки',
    speed: 'Скорость',
    normal: 'Нормальная',
    quality: 'Качество',
    loop: 'Повтора',
    start: 'Начало',
    end: 'Конец',
    all: 'Все',
    reset: 'Reset',
    disabled: 'Отключено',
    advertisement: 'Реклама'
};